import { mkdir, writeFile, readdir, unlink } from "fs/promises";
import { join } from "path";
import { VOSS_TRAEFIK_DYNAMIC_DIR, validateHostname } from "@voss/shared";
import { getDb, schema } from "../db";
import { eq } from "drizzle-orm";

const DOMAIN = process.env.VOSS_DOMAIN ?? "localhost";

interface TraefikRoute {
  projectName: string;
  containerName: string;
  port: number;
  domains: string[];
}

/**
 * Regenerate Traefik dynamic config for a project.
 * Writes atomic YAML to the dynamic config directory.
 * Traefik watches this directory and auto-reloads.
 */
export async function updateTraefikConfig(route: TraefikRoute): Promise<void> {
  await mkdir(VOSS_TRAEFIK_DYNAMIC_DIR, { recursive: true });

  const routerName = `voss-${route.projectName}`;
  const hosts = [
    `${route.projectName}.${DOMAIN}`,
    ...route.domains,
  ];

  const isIpDomain = /^\d+\.\d+\.\d+\.\d+$/.test(DOMAIN);
  // Validate all domains before writing YAML to prevent injection
  const realDomains = route.domains.filter(Boolean).filter((h) => !validateHostname(h));
  const hasRealDomains = realDomains.length > 0;

  let routers = "";

  // Always add IP/catch-all route for direct access
  if (isIpDomain) {
    routers += `
    ${routerName}-ip:
      rule: "PathPrefix(\`/\`)"
      entryPoints:
        - web
      service: ${routerName}
      priority: 1`;
  }

  // Add HTTPS routes for real domains
  if (hasRealDomains) {
    const domainRule = realDomains.map((h) => `Host(\`${h}\`)`).join(" || ");
    routers += `
    ${routerName}:
      rule: "${domainRule}"
      entryPoints:
        - websecure
      service: ${routerName}
      tls:
        certResolver: letsencrypt
      priority: 10
    ${routerName}-http:
      rule: "${domainRule}"
      entryPoints:
        - web
      middlewares:
        - redirect-to-https
      service: ${routerName}
      priority: 10`;
  }

  const yaml = `# Auto-generated by voss-server. Do not edit.
http:
  routers:${routers}
  services:
    ${routerName}:
      loadBalancer:
        servers:
          - url: "http://${route.containerName}:${route.port}"
`;

  // Atomic write: write to temp file, then rename
  const filePath = join(VOSS_TRAEFIK_DYNAMIC_DIR, `${route.projectName}.yml`);
  const tmpPath = `${filePath}.tmp`;
  await writeFile(tmpPath, yaml, "utf-8");
  const { rename } = await import("fs/promises");
  await rename(tmpPath, filePath);
}

/**
 * Remove Traefik config for a project.
 */
export async function removeTraefikConfig(projectName: string): Promise<void> {
  const filePath = join(VOSS_TRAEFIK_DYNAMIC_DIR, `${projectName}.yml`);
  try {
    await unlink(filePath);
  } catch {
    // File may not exist
  }
}

/**
 * Reconcile Traefik configs from database state.
 * Called at server startup to ensure Traefik matches reality.
 */
export async function reconcileTraefikConfigs(): Promise<void> {
  const db = getDb();
  await mkdir(VOSS_TRAEFIK_DYNAMIC_DIR, { recursive: true });

  // Get all active aliases with their deployments
  const allAliases = db.select().from(schema.aliases).all();

  const activeProjects = new Set<string>();

  for (const alias of allAliases) {
    const deployment = db
      .select()
      .from(schema.deployments)
      .where(eq(schema.deployments.id, alias.deploymentId))
      .get();

    const project = db
      .select()
      .from(schema.projects)
      .where(eq(schema.projects.id, alias.projectId))
      .get();

    if (!deployment?.containerName || !project) continue;

    // Get custom domains
    const projectDomains = db
      .select()
      .from(schema.domains)
      .where(eq(schema.domains.projectId, project.id))
      .all();

    const config = JSON.parse(deployment.configSnapshot);
    const port = 3000; // TODO: get from runner config

    await updateTraefikConfig({
      projectName: project.name,
      containerName: deployment.containerName,
      port,
      domains: projectDomains.map((d) => d.hostname),
    });

    activeProjects.add(project.name);
  }

  // Remove stale configs (projects no longer active)
  try {
    const existingFiles = await readdir(VOSS_TRAEFIK_DYNAMIC_DIR);
    for (const file of existingFiles) {
      if (!file.endsWith(".yml")) continue;
      const name = file.replace(".yml", "");
      if (name === "middlewares" || name === "voss-dashboard") continue;
      if (!activeProjects.has(name)) {
        await unlink(join(VOSS_TRAEFIK_DYNAMIC_DIR, file));
      }
    }
  } catch {
    // Directory may not exist yet
  }
}

/**
 * Write the default Traefik middlewares config.
 */
export async function writeDefaultMiddlewares(): Promise<void> {
  await mkdir(VOSS_TRAEFIK_DYNAMIC_DIR, { recursive: true });

  const yaml = `# Default middlewares for voss
http:
  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: true
`;

  await writeFile(
    join(VOSS_TRAEFIK_DYNAMIC_DIR, "middlewares.yml"),
    yaml,
    "utf-8"
  );
}
